[package]
name = "rusticoin"
version = "0.1.0"
edition = "2021"
description = "Cryptocurrency implementation with Rust"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.18"
data-encoding = "2.3.3"
